# -*- coding: utf-8 -*-
"""CineWatch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aYzYfel8K1Opaorwg59m3DaKyqoE59--
"""

import numpy as np
import pandas as pd

movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

movies.head(1)

credits.head(1)  # Cast and crew

"""Merging movies and credits dataset on title column"""

movies = movies.merge(credits,on='title')
movies.head(1)

"""Select relevant columns"""

movies = movies[['id','title','overview','genres','keywords','cast','crew']]
movies.head(1)

movies.isnull().sum()

movies.dropna(inplace=True)

movies.duplicated().sum()

movies.iloc[0].genres  #Preprocess genre

"""Convert string to list"""

import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]') #Removing streing format

def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

movies['genres'].apply(convert)

movies['genres'] = movies['genres'].apply(convert)

movies['keywords'] = movies['keywords'].apply(convert)  #Preprocess Keywords
movies.head(1)

movies['cast'][0]   #Preprocessing cast

def convert3(obj):
    L = []
    c=0
    for i in ast.literal_eval(obj):
        if(c!=3):
            L.append(i['name'])
            c+=1
        else:
            break
    return L
movies['cast'] = movies['cast'].apply(convert3)

movies['cast']

movies['crew'][0]  #Preprocessing crew

def fetchDirector(obj):
    L = []
    for i in ast.literal_eval(obj):
        if(i['job']=='Director'):
            L.append(i['name'])
            break
    return L
movies['crew'] = movies['crew'].apply(fetchDirector)

movies['crew']

movies['overview'][0]   #Preprocess overview

movies['overview'] = movies['overview'].apply(lambda x:x.split())
movies['overview'][0]

movies.head(1)

movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

movies['tags'] = movies['overview'] + movies['genres'] + movies['cast'] + movies['crew']
movies.head()   #One tag

new_df = movies[['id','title','tags']]
new_df.head()

new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

new_df['tags'][0]

new_df['tags'] =  new_df['tags'].apply(lambda x:x.lower())
new_df['tags'][0]

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')

vectors = cv.fit_transform(new_df['tags']).toarray()
vectors

import nltk
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

new_df['tags'] = new_df['tags'].apply(stem)

from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectors)
cosine_similarity(vectors)

movie = "Avatar"
movie_index = new_df[new_df['title']==movie].index[0]

# Recommendation function
def recommend(movie):

    # find the index of the movie
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]

    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:6]

    # print recommended movies
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

recommend('Twilight')

"""Integrating Streamlit"""

import  streamlit as st
st.title('CineWatch Recommendation System')

import pickle
pickle.dump(new_df.to_dict(),open('movies.pkl','wb'))

import streamlit as st
import pickle
import pandas as pd

movies_dict = pickle.load(open('movies.pkl','rb'))
movies = pd.DataFrame(movies_dict)

st.title('Movie Recommender System')

selected_movie_name = st.selectbox(
"Type or select a movie from the dropdown",
 movies['title'].values
)

pickle.dump(similarity,open('similarity.pkl','wb'))

similarity = pickle.load(open('similarity.pkl','rb'))
def recommend(movie):
    movie_index = movies[movies['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:6]

    recommended_movies = []
    for i in movies_list:
             recommended_movies.append(movies.iloc[i[0]].title)
    return recommended_movies

if st.button('Show Recommendation'):
    recommendations = recommend(selected_movie_name)

    for i in recommendations:
        st.write(i)

# @title
import requests

def fetch_poster(movie_id):
    url = "https://api.themoviedb.org/3/movie/{}?api_key='TMBD_posters'&language=en-US".format(movie_id)
    data = requests.get(url)
    data = data.json()
    poster_path = data['poster_path']
    full_path = "https://image.tmdb.org/t/p/w500/" + poster_path
    return full_path

import  streamlit as st

import pickle
import pandas as pd
import requests

st.title('Movie Recommender System')


def fetch_poster(movie_id):
    url = "https://api.themoviedb.org/3/movie/{}?api_key='72ad733ac015d518772afe9e7c7ae01a'&language=en-US".format(movie_id)
    data = requests.get(url)
    data = data.json()
    poster_path = data['poster_path']
    full_path = "https://image.tmdb.org/t/p/w500/" + poster_path
    return full_path

def recommend(movie):
    movie_index = movies[movies['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:6]

    recommended_movies = []
    recommended_movie_posters = []

    for i in movies_list:
        # fetch the movie poster
        movie_id = movies.iloc[i[0]].id
        recommended_movies.append(movies.iloc[i[0]].title)
        recommended_movie_posters.append(fetch_poster(movie_id))

    return recommended_movies,recommended_movie_posters

movies_dict = pickle.load(open('movies.pkl','rb'))
movies = pd.DataFrame(movies_dict)
similarity = pickle.load(open('similarity.pkl','rb'))


selected_movie_name = st.selectbox(
    "Type or select a movie ",
    movies['title'].values
)
if st.button('Show Recommendation'):
    names,posters = recommend(selected_movie_name)

    #display with the columns
    col1, col2, col3, col4, col5 = st.columns(5)
    with col1:
        st.text(names[0])
        st.image(posters[0])
    with col2:
        st.text(names[1])
        st.image(posters[1])
    with col3:
        st.text(names[2])
        st.image(posters[2])
    with col4:
        st.text(names[3])
        st.image(posters[3])
    with col5:
        st.text(names[4])
        st.image(posters[4])